const SHORTIE_DURATION = 40;
const BIG_SCREEN_WIDTH = 1280;
const MIDDLE_SCREEN_WIDTH = 990;
const LITTLE_SCREEN_WIDTH = 630;
const BIG_START_NUMBER = 16;
const MIDDLE_START_NUMBER = 12;
const LITTLE_START_NUMBER = 8;
const MIN_START_NUMBER = 5;
const BIG_ADD_NUMBER = 4;
const MIDDLE_ADD_NUMBER = 3;
const LITTLE_ADD_NUMBER = 2;

export {
  SHORTIE_DURATION,
  BIG_SCREEN_WIDTH,
  MIDDLE_SCREEN_WIDTH,
  LITTLE_SCREEN_WIDTH,
  BIG_START_NUMBER,
  MIDDLE_START_NUMBER,
  LITTLE_START_NUMBER,
  MIN_START_NUMBER,
  BIG_ADD_NUMBER,
  MIDDLE_ADD_NUMBER,
  LITTLE_ADD_NUMBER
};
